name: myapp
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7

  # State Management
  provider: ^6.1.2

  # Media & Permissions
  photo_manager: ^3.1.2
  video_thumbnail: ^0.5.3
  cached_network_image: ^3.3.1
  permission_handler: ^11.3.1

  # Utilities
  path_provider: ^2.1.5
  shared_preferences: ^2.2.3
  logger: ^2.3.0
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  analyzer: ^6.4.1

flutter:
  uses-material-design: true
